### ISSUE TITLE
python error after using Taskify (spurious comma)

### ISSUE THREAD

**Issue by missirol** [cms-sw/hlt-confdb#32]
Hi @Sam-Harper, I tried to Taskify a menu, and convert it to python via `hltGetConfiguration`, and I ran into one (and only one) syntax error
```
process.DQMHistograms = cms.EndPath( ,process.DQMHistogramsTask )
```
Is that possible, and does it require a fix in `hlt-confdb`, or elsewhere?

One more small comment: would it be possible to add a space between comma and task? Red is what I see now:
```diff
-process.ScoutingCaloMuonOutput = cms.EndPath( process.hltPreScoutingCaloMuonOutput + process.hltOutputScoutingCaloMuon,process.ScoutingCaloMuonOutputTask )
+process.ScoutingCaloMuonOutput = cms.EndPath( process.hltPreScoutingCaloMuonOutput + process.hltOutputScoutingCaloMuon, process.ScoutingCaloMuonOutputTask )
```

**Comment by Sam-Harper** [comment]
Sure.  Thanks for the heads up. The fix is actually needed in hltGetConfiguration.  Confdb can adjust the comma spacing though.

**Comment by missirol** [comment]
Okay, thanks. If it's `hltGetConfiguration`, I can try to have a look (but feel free to go ahead, when you have time).

**Comment by missirol** [comment]
The related changes should be in https://github.com/cms-sw/cmssw/pull/35917 and https://github.com/cms-sw/hlt-confdb/pull/33. If I'm missing something.. let me know.

**Comment by missirol** [comment]
Issue solved in V03-01-00.
