### ISSUE TITLE
update of `JPythonParser` to handle `cms.ConditionalTask`

### ISSUE THREAD

**Issue by missirol** [cms-sw/hlt-confdb#50]
`ConfDB` internally has one single container for "Tasks", while CMSSW has two types of "Tasks", i.e. `cms.Task` and `cms.ConditionalTask`.

`ConditionalTask` was designed with HLT's needs in mind (see https://github.com/cms-sw/cmssw/issues/36938), and the current plan is to support only `ConditionalTask` in `ConfDB` moving forward.

 - https://github.com/cms-sw/hlt-confdb/pull/49 changed the python output of `ConfDB` to go from `cms.Task` to `cms.ConditionalTask`.

 - The python parser, i.e. `JPythonParser` (to create a ConfDB menu starting from a python config) still needs to be updated to support `ConditionalTask`s.

**Comment by missirol** [comment]
If we don't plan to support `cms.Task` at all moving forward, it might be sufficient to replace "`_Process__tasks`" with "`_Process__conditionaltasks`" in [`JPythonParser`](https://github.com/cms-sw/hlt-confdb/blob/e02228812406fbfa911bd456d2f0f013fb2b2dbe/src/confdb/parser/JPythonParser.java).

If we want to be able to parse both `cms.Task` and `cms.ConditionalTask` into the one "Task" container used internally by ConfDB, then the update is a bit more complex (but I assume we don't want to support both in parsing, since we only support one in output).

**Comment by Sam-Harper** [comment]
it was a similar amount of effort to support both. They both parse to the same place though so their type is lost but  I think that is what we want. Done in the PR and tested with the 12_5_0 GRun menu and 12_3_0 GRun menu, it can parse ConditionalTask and Task configs just fine.

**Comment by missirol** [comment]
Thanks, Sam!
