### ISSUE TITLE
`SmartPrescale` table empties `triggerConditions` based on `DatasetPath`s

### ISSUE THREAD

**Issue by missirol** [cms-sw/hlt-confdb#60]
Hi @Sam-Harper , I encountered a problem with the ConfDB GUI.

The latest combined table (`/dev/CMSSW_12_4_0/HLT/V133`) contains a new HLT path that uses a `TriggerResultsFilter` module to select events accepted by a PD
```py
hltMuonTriggerResultsFilter = cms.EDFilter( "TriggerResultsFilter",
    usePathStatus = cms.bool( True ),
    hltResults = cms.InputTag( "" ),
    l1tResults = cms.InputTag( "" ),
    l1tIgnoreMaskAndPrescale = cms.bool( False ),
    throw = cms.bool( True ),
    triggerConditions = cms.vstring( 'Dataset_Muon' )
)
```
This can be saved and works without problems, but if one opens the "Edit SmartPrescales" window, then `hltMuonTriggerResultsFilter.triggerConditions` becomes empty from there on out (and one has to fix it manually).

If confirmed, it would be good to fix this, otherwise this will be missed eventually, and we'll have a bug in that trigger.

With some trial&error, I find that the following [*] does the trick, but I haven't tested it extensively.

Could you please have a look?

[*]
```diff
diff --git a/src/confdb/data/SmartPrescaleTable.java b/src/confdb/data/SmartPrescaleTable.java
index 6b7afe7d..a4fc0c0a 100644
--- a/src/confdb/data/SmartPrescaleTable.java
+++ b/src/confdb/data/SmartPrescaleTable.java
@@ -105,7 +105,7 @@ public class SmartPrescaleTable {
                 }
             } else {
                 path = config.path(strPath);
-                if ((path != null) && (!path.isStdPath())) path = null;
+                if ((path != null) && !(path.isStdPath() || path.isDatasetPath())) path = null;
             }
         }
         return (path != null);
```

**Comment by Sam-Harper** [comment]
Thanks Marino, 

I'll have a look now

**Comment by Sam-Harper** [comment]
Ah yes I agree with the solution. As you have found out, this is to check if the path exists in the menu and its a standard path. So now the path is a dataset path, its not working. 

 Its intention was to ensure it wasnt an End or FinalPath which can not be added.  Dataset paths are perfectly valid to have as inputs so the OR is correct and this is fine.  
 
 Thanks for fixing the bug, I assume you'll submit the PR

**Comment by missirol** [comment]
Thanks for having a look! Sure, I'll make the PR.
