### ISSUE TITLE
Process name is reset when copying from offline to online database.

### ISSUE THREAD

**Issue by trtomei** [cms-sw/hlt-confdb#87]
Process name is reset (i.e., set to an empty string) when copying from offline to online database.

 - Offline menu is [/online/special/2024/v1.1/Splashes/V3](https://cmshltcfg.app.cern.ch/open?cfg=%2Fonline%2Fspecial%2F2024%2Fv1.1%2FSplashes%2FV3&db=offline-run3). It has "HLT" process name.
 - Online is [/cdaq/special/2024/Splashes/v1.1.0/HLT/V1](https://cmshltcfg.app.cern.ch/open?cfg=%2Fcdaq%2Fspecial%2F2024%2FSplashes%2Fv1.1.0%2FHLT%2FV1&db=online/). It has empty process name.

**Comment by Sam-Harper** [comment]
fixed by https://github.com/cms-sw/hlt-confdb/pull/93
